# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: payload.proto for package ''

require 'grpc'
require 'payload_pb'

module DemogRPC
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'DemogRPC'

    rpc :GetResponseFromPayload, ::PayloadMessage, ::ResponseMessage
  end

  Stub = Service.rpc_stub_class
end
