version: "3.8"

services:

  postgres:
    hostname: postgres
    build:
      context: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DATABASES=${POSTGRES_NAME:-decisioning}
    ports:
      - "5432:5432"

  python-grpc-server:
    tty: true
    stdin_open: true
    image: python-grpc-server:latest
    build: .
    env_file:
      - .env
    ports:
      - "8088:8088"
    depends_on:
      - postgres
