# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayload.proto\"c\n\x0ePayloadMessage\x12\x15\n\rcustomer_name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\r\x12\x0f\n\x07\x63reated\x18\x03 \x01(\t\x12\x0c\n\x04\x63ost\x18\x04 \x01(\r\x12\x0f\n\x07id_uuid\x18\x05 \x01(\t\"B\n\x0fResponseMessage\x12\x15\n\rresponse_code\x18\x01 \x01(\x05\x12\x18\n\x10response_message\x18\x02 \x01(\t2I\n\x08\x44\x65mogRPC\x12=\n\x16GetResponseFromPayload\x12\x0f.PayloadMessage\x1a\x10.ResponseMessage\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PAYLOADMESSAGE']._serialized_start=17
  _globals['_PAYLOADMESSAGE']._serialized_end=116
  _globals['_RESPONSEMESSAGE']._serialized_start=118
  _globals['_RESPONSEMESSAGE']._serialized_end=184
  _globals['_DEMOGRPC']._serialized_start=186
  _globals['_DEMOGRPC']._serialized_end=259
# @@protoc_insertion_point(module_scope)
