# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import payload_pb2 as payload__pb2


class DemogRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetResponseFromPayload = channel.unary_unary(
                '/DemogRPC/GetResponseFromPayload',
                request_serializer=payload__pb2.PayloadMessage.SerializeToString,
                response_deserializer=payload__pb2.ResponseMessage.FromString,
                )


class DemogRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetResponseFromPayload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DemogRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetResponseFromPayload': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResponseFromPayload,
                    request_deserializer=payload__pb2.PayloadMessage.FromString,
                    response_serializer=payload__pb2.ResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DemogRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DemogRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetResponseFromPayload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DemogRPC/GetResponseFromPayload',
            payload__pb2.PayloadMessage.SerializeToString,
            payload__pb2.ResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
